Repository red-hat-storage/rhcs-qa, pull requests merged in 2020-07, with the labels that each got.

#106 ceph.conf.template: adding back from rh-nautilus
  qa/tasks/ceph.conf.template
Labels: RGW

#107 Added Initial cephadm smoke test
  qa/rh/downstream.yaml
  qa/suites/smoke/cephadm/%
  qa/suites/smoke/cephadm/clusters/3-node.yaml
  qa/suites/smoke/cephadm/tasks.yaml
  qa/tasks/ceph.py
  qa/tasks/ceph_manager.py
  qa/tasks/cephadm.conf
  qa/tasks/cephfs/cephfs_test_case.py
  qa/tasks/cephfs/filesystem.py
  qa/tasks/cephfs/fuse_mount.py
  qa/tasks/cephfs/kernel_mount.py
  qa/tasks/cephfs/mount.py
  qa/tasks/daemonwatchdog.py
  qa/tasks/mgr/mgr_test_case.py
  qa/tasks/rhcephadm.py
  qa/tasks/thrasher.py
  qa/tasks/thrashosds-health.yaml
  qa/tasks/thrashosds.py
  qa/tasks/util/rados.py
  qa/tasks/util/rgw.py
  qa/tasks/vstart_runner.py
  src/cephadm/CMakeLists.txt
  src/cephadm/cephadm
  src/cephadm/mypy.ini
  src/cephadm/samples/alertmanager.json
  src/cephadm/samples/grafana.json
  src/cephadm/samples/nfs.json
  src/cephadm/samples/prometheus.json
  src/cephadm/samples/rgw_ssl.json
  src/cephadm/tests/__init__.py
  src/cephadm/tests/test_cephadm.py
  src/cephadm/tox.ini
  src/cephadm/vstart-cleanup.sh
  src/cephadm/vstart-smoke.sh
Labels: Cephadm, DNM, needs-qa

#117 move rhel repos to downstream.yaml
  qa/rh/downstream.yaml
Labels: infra, rh-luminous

#116 rename repos to rhel_repos in downstream.yaml
  qa/rh/downstream.yaml
Labels: infra, rh-nautilus
